---
name: CI
on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  build:
    name: Run tests
    strategy:
      fail-fast: true
      matrix:
        neovim_branch: ['v0.5.0', 'master']
    runs-on: ubuntu-latest
    env:
      NEOVIM_BRANCH: ${{ matrix.neovim_branch }}

    steps:
      # Checkout packer
      - uses: actions/checkout@v2

      # Copied/adapted from lewis6991/gitsigns.nvim
      - name: Setup build dependencies
        run: |
          sudo apt update &&
          sudo apt install -y \
            autoconf \
            automake \
            cmake \
            g++ \
            gettext \
            gperf \
            libjemalloc-dev \
            libluajit-5.1-dev \
            libmsgpack-dev \
            libtermkey-dev \
            libtool \
            libtool-bin \
            libunibilium-dev \
            libvterm-dev \
            lua-bitop \
            lua-lpeg \
            lua-mpack \
            ninja-build \
            pkg-config \
            unzip

      # - name: Cache Neovim
      #   uses: actions/cache@v2
      #   with:
      #     path: neovim
      #     key: build-${{env.NEOVIM_BRANCH}}

      - name: Build Neovim
        run: |
          git clone --depth 1 https://github.com/neovim/neovim --branch ${{env.NEOVIM_BRANCH}}
          make -C neovim

      - name: Run tests
        run: |
          export PATH="neovim/build/bin:${PATH}"
          export VIM="neovim/runtime"
          make test
