name: Formating and doc generation

on: [push, pull_request_target]

jobs:
  postprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format with stylua"
          branch: ${{ github.head_ref }}

      - name: "Auto Generate docs"
        uses: docker://leiserfg/md2vim
        with:
          args:  '-desc  "Luasnip Snippet Engine"  DOC.md doc/luasnip.txt'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
